baseURL = "https://kubenews.net"
title = "Kubernetes News"
theme = ["github.com/luizdepra/hugo-coder"]
languagecode = "en"

[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = 'github.com/luizdepra/hugo-coder'

[params]
    author = ""
    info = "Pull Requests Wanted!"
    description = "Kubernetes and Cloud Native Computing Foundation News Sources - How do you keep up with Kubernetes?"
    keywords = "cloud native,newsletters,news,kubernetes"

    hideCredits = true
    hideCopyright = true

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/chris-short/kubenews.net"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/ChrisShort"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://linkedin.com/in/thechrisshort/"
[[params.social]]
    name = "Curated by Chris Short"
    weight = 4
    url = "https://chrisshort.me"

[[params.sites]]
    name = "KubeWeekly"
    description = "CNCF curated weekly digest of all things Kubernetes!"
    weight = 1
    url = "https://kubeweekly.io"
[[params.sites]]
    name = "Kubernetes Blog"
    description = "The official Kubernetes blog"
    weight = 2
    url = "https://kubernetes.io/blog/"
[[params.sites]]
    name = "Kubernetes Contributors"
    description = "This site is the home of contributor documentation, and serves as a starting point for your journey as a Kubernetes contributor. It is intended to be the hub for all things related to the Kubernetes Contributor experience."
    weight = 3
    url = "https://www.kubernetes.dev/"
[[params.sites]]
    name = "DevOps'ish"
    description = "DevOps, Cloud Native, Open Source, and the 'ish in between."
    weight = 4
    url = "https://devopsish.com/"
[[params.sites]]
    name = "EKS News"
    description = "EKS News aims to be to go to newsletter for all things AWS EKS, adjacent AWS services, Kubernetes, and Cloud Native"
    weight = 5
    url = "https://eks.news/"
[[params.sites]]
    name = "PodCTL"
    description = "A podcast focused on Containers, Kubernetes and Cloud-native application development."
    weight = 6
    url = "https://www.podctl.com/"
[[params.sites]]
    name = "Kubernetes Podcast from Google"
    description = "A weekly news and interview show with insight from the Kubernetes community."
    weight = 7
    url = "https://kubernetespodcast.com/"
[[params.sites]]
    name = "Last Week in Kubernetes Development"
    description = "LWKD is a weekly newsletter summarizing code activity in the Kubernetes project: merges, PRs, deprecations, version updates, release schedules, and the weekly community meeting."
    weight = 8
    url = "http://lwkd.info/"
[[params.sites]]
    name = "The New Stack"
    description = "A digest of the week's most important stories & analyses about the services and infrastructures that developers build and the cultural impact that has on the way we work and live."
    weight = 14
    url = "https://thenewstack.io/newsletter-archive"
[[params.sites]]
    name = "nativecloud.dev"
    description = "A weekly summary covering Cloud Native Community, Container technologies and Open Source development."
    weight = 16
    url = "https://nativecloud.dev"
[[params.sites]]
    name = "Kubernetes README"
    description = "What books ðŸ“š to read to learn more about Kubernetes"
    weight = 998
    url = "https://kubereadme.com/"
[[params.sites]]
    name = "DevOps Newsletters"
    description = "Looking for a list of newsletters like this related to DevOps? I've got you covered."
    weight = 999
    url = "https://devopsnewsletters.com/"
